export interface Message {
    id: string
    content: string
    role: "user" | "assistant"
    timestamp: Date
    userId?: string
    sessionId?: string
}

export interface ChatSession {
    id: string
    title: string
    lastMessage: string
    timestamp: Date
    userId: string
    messageCount?: number
}

export interface MemoryItem {
    id: string
    content: string
    category: string
    importance: number
    timestamp: Date
    autoGenerated: boolean
    sessionId?: string
    messageContext?: string
}

export interface UserMemory {
    userId: string
    memories: MemoryItem[]
    lastUpdated: Date
    totalMemories: number
    storageUsed: number // in bytes
    storageLimit: number // in bytes
}

export interface ChatState {
    messages: Message[]
    isLoading: boolean
    isTyping: boolean
    currentSessionId: string
    error: string | null
}
